stages:
  - deploy

deploy2dev:
  stage: deploy
  only:
    - main
  image:
   name: debian:12.5
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SSH_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$SSH_IP "
      cd /home/deploy/deploy/docs &&
      git pull &&
      docker compose -f docker-compose.prod.yml build &&
      docker compose -f docker-compose.prod.yml up -d --force-recreate 
      "
