concurrent = 15
check_interval = 5
shutdown_timeout = 5400

[session_server]
session_timeout = 1800

[[runners]]
name = "RUNSYSTEMxCICD PROD"
url = "https://devops.runsystem.info/"
clone_url = "https://devops.runsystem.info"
id = 256
token = "qg6U14TQ8MM3McRan8JW"
token_obtained_at = 2023-04-17T10:11:05Z
token_expires_at = 0001-01-01T00:00:00Z
executor = "docker"
limit = 15
[runners.cache]
MaxUploadedArchiveSize = 0
[runners.docker]
tls_verify = false
image = "ubuntu:22.04"
privileged = false
disable_entrypoint_overwrite = false
oom_kill_disable = false
disable_cache = false
volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
shm_size = 0
cpus = "3"
memory = "8G"
