route:
  group_by: ['cluster']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  routes:
    - match:
        severity: critical
      receiver: 'mattermost-critical'

receivers:
  - name: 'mattermost-critical'
    slack_configs:
      - send_resolved: true
        api_url: 'https://chat.runsystem.vn/api/v4/posts'
        channel: "fsiwicrbwtdr3cwtm9uszqtwqo"
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"